  services:
  # Flask Web Service
  - type: web
    name: vidsnapai-web
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: gunicorn main:app

    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
